/**
 * Picks random products from a live IKEA product response and writes them as
 * typed fixtures for the component showcase.
 *
 * Usage: npm run fixtures -w frontend [-- <country> <language>]   (default: se sv)
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { createIkeaClient, isSupportedMarket } from 'ikea-tinder-backend/server';

const SAMPLE_SIZE = 5;
const OUTPUT_FILE = new URL('../src/lib/fixtures/product.ts', import.meta.url);

const [country = 'se', language = 'sv'] = process.argv.slice(2);

if (!isSupportedMarket(country, language)) {
	console.error(`Unknown market '${country}/${language}'. See GET /api/markets for valid pairs.`);
	process.exit(1);
}

const result = await createIkeaClient().fetchNewProducts({ country, language });
if (!result.ok) {
	console.error('Could not fetch products from IKEA:', result.error);
	process.exit(1);
}

// Fisher–Yates on a copy, then take the first few: random and without duplicates.
const shuffled = [...result.value];
for (let i = shuffled.length - 1; i > 0; i--) {
	const j = Math.floor(Math.random() * (i + 1));
	[shuffled[i], shuffled[j]] = [shuffled[j]!, shuffled[i]!];
}
const products = shuffled.slice(0, SAMPLE_SIZE);
if (products.length === 0) {
	console.error(`IKEA returned no products for ${country}/${language}.`);
	process.exit(1);
}

const source = `// Generated by scripts/generate-product-fixture.ts from a live ${country}/${language} product response.
// Regenerate with: npm run fixtures -w frontend
import type { Product } from 'ikea-tinder-backend/server';

export const sampleProducts: Product[] = ${JSON.stringify(products, null, '\t')};

export const sampleProduct: Product = sampleProducts[0]!;
`;

await mkdir(new URL('.', OUTPUT_FILE), { recursive: true });
await writeFile(OUTPUT_FILE, source);
console.log(`Wrote ${products.map((product) => product.name).join(', ')} to src/lib/fixtures/product.ts`);
