// Generated by scripts/generate-product-fixture.ts from a live se/sv product response.
// Regenerate with: npm run fixtures -w frontend
import type { Product } from 'ikea-tinder-backend/server';

export const sampleProducts: Product[] = [
	{
		"id": "s99627253",
		"name": "RAMNEFJÄLL",
		"typeName": "Klädd sängstomme",
		"designText": "Idekulla beige/Luröy",
		"imageUrl": "https://www.ikea.com/se/sv/images/products/ramnefjaell-klaedd-saengstomme-idekulla-beige-luroey__1540717_pe1017855_s5.jpg",
		"imageAlt": "RAMNEFJÄLL beige säng: böjd sänggavel, vadderad, stoppad, rena linjer.",
		"contextImageUrl": "https://www.ikea.com/se/sv/images/products/ramnefjaell-klaedd-saengstomme-idekulla-beige-luroey__1540770_pe1017894_s5.jpg",
		"url": "https://www.ikea.com/se/sv/p/ramnefjaell-klaedd-saengstomme-idekulla-beige-luroey-s99627253/",
		"price": {
			"amount": 2395,
			"currency": "SEK",
			"formatted": "2 395:-",
			"previous": null
		},
		"rating": {
			"value": 4.1,
			"count": 202
		},
		"images": [
			{
				"url": "https://www.ikea.com/se/sv/images/products/ramnefjaell-klaedd-saengstomme-idekulla-beige-luroey__1540717_pe1017855_s5.jpg",
				"alt": "RAMNEFJÄLL beige säng: böjd sänggavel, vadderad, stoppad, rena linjer."
			},
			{
				"url": "https://www.ikea.com/se/sv/images/products/ramnefjaell-klaedd-saengstomme-idekulla-beige-luroey__1540770_pe1017894_s5.jpg",
				"alt": "Beige RAMNEFJÖLL-säng med grått paisleyuppsläpning, rosa vägg, träsängbord med lampa."
			},
			{
				"url": "https://www.ikea.com/se/sv/images/products/ramnefjaell-klaedd-saengstomme-idekulla-beige-luroey__1540719_pe1017863_s5.jpg",
				"alt": "Säng med mjuk, böjd sänggavel och mönstrat täcke, vilket ger komfort och stil. Nattduksbord med lampa bredvid."
			},
			{
				"url": "https://www.ikea.com/se/sv/images/products/ramnefjaell-klaedd-saengstomme-idekulla-beige-luroey__1540721_pe1017858_s5.jpg",
				"alt": "Mysig säng med mönstrat sängkläder och tunna gardiner."
			},
			{
				"url": "https://www.ikea.com/se/sv/images/products/ramnefjaell-klaedd-saengstomme-idekulla-beige-luroey__1540720_pe1017857_s5.jpg",
				"alt": "Beige klädd säng med dragkedja för förvaring, med en mysig, vadderad sänggavel och ren design."
			},
			{
				"url": "https://www.ikea.com/se/sv/images/products/ramnefjaell-klaedd-saengstomme-idekulla-beige-luroey__1540722_pe1017859_s5.jpg",
				"alt": "Närbild på ett beige hörn med stoppad sängram. Visar snygg söm och mjukt tyg, vilket framhäver kvaliteten."
			},
			{
				"url": "https://www.ikea.com/se/sv/images/products/ramnefjaell-klaedd-saengstomme-idekulla-beige-luroey__1540755_pe1017884_s5.jpg",
				"alt": "Beige klädd sängramkant, maskintvättbar; visar mjuk, vadderad sänggavel."
			},
			{
				"url": "https://www.ikea.com/se/sv/images/products/ramnefjaell-klaedd-saengstomme-idekulla-beige-luroey__1540753_pe1017882_s5.jpg",
				"alt": "Beige tyg med intrikat, tätt vävt mönster. Mjuk, hållbar textur, troligen återvunnen polyester."
			},
			{
				"url": "https://www.ikea.com/se/sv/images/products/ramnefjaell-klaedd-saengstomme-idekulla-beige-luroey__1540754_pe1017883_s5.jpg",
				"alt": "Tvättmaskinen öppen, med grå kläder synliga inuti."
			}
		],
		"measurement": "180x200 cm",
		"badge": null,
		"colors": [
			{
				"name": "beige",
				"hex": "#f4f3d7"
			}
		],
		"categories": [
			"Sängar & madrasser",
			"Sängar",
			"Dubbelsängar"
		],
		"variantCount": 11
	},
	{
		"id": "30635552",
		"name": "EKTORP",
		"typeName": "Klädsel till 3-sitssoffa",
		"designText": "Mångbyn brun/flerfärgad",
		"imageUrl": "https://www.ikea.com/se/sv/images/products/ektorp-klaedsel-till-3-sitssoffa-mangbyn-brun-flerfaergad__1545764_pe1019854_s5.jpg",
		"imageAlt": "EKTORP Klädsel till 3-sitssoffa, Mångbyn brun/flerfärgad",
		"contextImageUrl": "https://www.ikea.com/se/sv/images/products/ektorp-klaedsel-till-3-sitssoffa-mangbyn-brun-flerfaergad__1546258_pe1019897_s5.jpg",
		"url": "https://www.ikea.com/se/sv/p/ektorp-klaedsel-till-3-sitssoffa-mangbyn-brun-flerfaergad-30635552/",
		"price": {
			"amount": 1495,
			"currency": "SEK",
			"formatted": "1 495:-",
			"previous": null
		},
		"rating": {
			"value": 4.2,
			"count": 433
		},
		"images": [
			{
				"url": "https://www.ikea.com/se/sv/images/products/ektorp-klaedsel-till-3-sitssoffa-mangbyn-brun-flerfaergad__1545764_pe1019854_s5.jpg",
				"alt": "EKTORP Klädsel till 3-sitssoffa, Mångbyn brun/flerfärgad"
			},
			{
				"url": "https://www.ikea.com/se/sv/images/products/ektorp-klaedsel-till-3-sitssoffa-mangbyn-brun-flerfaergad__1546258_pe1019897_s5.jpg",
				"alt": "EKTORP Klädsel till 3-sitssoffa, Mångbyn brun/flerfärgad"
			}
		],
		"measurement": null,
		"badge": null,
		"colors": [],
		"categories": [
			"Soffor & fåtöljer",
			"Sofföverdrag & fåtöljöverdrag",
			"EKTORP soffklädslar"
		],
		"variantCount": 26
	},
	{
		"id": "90640838",
		"name": "ANNAKAJSA",
		"typeName": "Rumsförmörkande gardiner, 1 par",
		"designText": "vit/med veckband",
		"imageUrl": "https://www.ikea.com/se/sv/images/products/annakajsa-rumsfoermoerkande-gardiner-1-par-vit-med-veckband__1533248_pe1015938_s5.jpg",
		"imageAlt": "ANNAKAJSA Rumsförmörkande gardiner, 1 par, vit/med veckband, 145x250 cm",
		"contextImageUrl": "https://www.ikea.com/se/sv/images/products/annakajsa-rumsfoermoerkande-gardiner-1-par-vit-med-veckband__1533235_pe1015931_s5.jpg",
		"url": "https://www.ikea.com/se/sv/p/annakajsa-rumsfoermoerkande-gardiner-1-par-vit-med-veckband-90640838/",
		"price": {
			"amount": 799,
			"currency": "SEK",
			"formatted": "799:-",
			"previous": null
		},
		"rating": {
			"value": 4.5,
			"count": 412
		},
		"images": [
			{
				"url": "https://www.ikea.com/se/sv/images/products/annakajsa-rumsfoermoerkande-gardiner-1-par-vit-med-veckband__1533248_pe1015938_s5.jpg",
				"alt": "ANNAKAJSA Rumsförmörkande gardiner, 1 par, vit/med veckband, 145x250 cm"
			},
			{
				"url": "https://www.ikea.com/se/sv/images/products/annakajsa-rumsfoermoerkande-gardiner-1-par-vit-med-veckband__1533235_pe1015931_s5.jpg",
				"alt": "ANNAKAJSA Rumsförmörkande gardiner, 1 par, vit/med veckband, 145x250 cm"
			},
			{
				"url": "https://www.ikea.com/se/sv/images/products/annakajsa-rumsfoermoerkande-gardiner-1-par-vit-med-veckband__1533155_pe1015899_s5.jpg",
				"alt": "ANNAKAJSA Rumsförmörkande gardiner, 1 par, vit/med veckband, 145x250 cm"
			},
			{
				"url": "https://www.ikea.com/se/sv/images/products/annakajsa-rumsfoermoerkande-gardiner-1-par-vit-med-veckband__1533157_pe1015900_s5.jpg",
				"alt": "ANNAKAJSA Rumsförmörkande gardiner, 1 par, vit/med veckband, 145x250 cm"
			},
			{
				"url": "https://www.ikea.com/se/sv/images/products/annakajsa-rumsfoermoerkande-gardiner-1-par-vit-med-veckband__1533156_pe1015901_s5.jpg",
				"alt": "ANNAKAJSA Rumsförmörkande gardiner, 1 par, vit/med veckband, 145x250 cm"
			},
			{
				"url": "https://www.ikea.com/se/sv/images/products/annakajsa-rumsfoermoerkande-gardiner-1-par-vit-med-veckband__1533249_pe1015937_s5.jpg",
				"alt": "ANNAKAJSA Rumsförmörkande gardiner, 1 par, vit/med veckband, 145x250 cm"
			}
		],
		"measurement": "145x250 cm",
		"badge": null,
		"colors": [
			{
				"name": "vit",
				"hex": "#ffffff"
			}
		],
		"categories": [
			"Gardiner & rullgardiner",
			"Gardiner",
			"Rumsförmörkande gardiner"
		],
		"variantCount": 4
	},
	{
		"id": "70628804",
		"name": "KOMPISHÄNG",
		"typeName": "Hängare för dörr",
		"designText": "beige",
		"imageUrl": "https://www.ikea.com/se/sv/images/products/kompishaeng-haengare-foer-doerr-beige__1508201_pe1009455_s5.jpg",
		"imageAlt": "KOMPISHÄNG Hängare för dörr, beige, 55 cm",
		"contextImageUrl": "https://www.ikea.com/se/sv/images/products/kompishaeng-haengare-foer-doerr-beige__1527612_pe1014233_s5.jpg",
		"url": "https://www.ikea.com/se/sv/p/kompishaeng-haengare-foer-doerr-beige-70628804/",
		"price": {
			"amount": 199,
			"currency": "SEK",
			"formatted": "199:-",
			"previous": null
		},
		"rating": {
			"value": 4.4,
			"count": 8
		},
		"images": [
			{
				"url": "https://www.ikea.com/se/sv/images/products/kompishaeng-haengare-foer-doerr-beige__1508201_pe1009455_s5.jpg",
				"alt": "KOMPISHÄNG Hängare för dörr, beige, 55 cm"
			},
			{
				"url": "https://www.ikea.com/se/sv/images/products/kompishaeng-haengare-foer-doerr-beige__1527617_pe1014238_s5.jpg",
				"alt": "KOMPISHÄNG Hängare för dörr, beige, 55 cm"
			},
			{
				"url": "https://www.ikea.com/se/sv/images/products/kompishaeng-haengare-foer-doerr-beige__1527612_pe1014233_s5.jpg",
				"alt": "KOMPISHÄNG Hängare för dörr, beige, 55 cm"
			},
			{
				"url": "https://www.ikea.com/se/sv/images/products/kompishaeng-haengare-foer-doerr-beige__1527616_pe1014234_s5.jpg",
				"alt": "KOMPISHÄNG Hängare för dörr, beige, 55 cm"
			}
		],
		"measurement": "55 cm",
		"badge": "På tillfälligt besök",
		"colors": [],
		"categories": [
			"Barnens IKEA",
			"Baby",
			"Barnrumsförvaring",
			"Väggförvaring för barn"
		],
		"variantCount": 0
	},
	{
		"id": "40635274",
		"name": "TULLSTA",
		"typeName": "Klädsel till fåtölj",
		"designText": "Sjölyckan mörkblå/beige rand",
		"imageUrl": "https://www.ikea.com/se/sv/images/products/tullsta-klaedsel-till-fatoelj-sjoelyckan-moerkbla-beige-rand__1547479_pe1020523_s5.jpg",
		"imageAlt": "Randig tygfåtölj på nära håll; blå toner, högkvalitativ bomull, rena linjer, slät textur.",
		"contextImageUrl": "https://www.ikea.com/se/sv/images/products/tullsta-klaedsel-till-fatoelj-sjoelyckan-moerkbla-beige-rand__1547479_pe1020523_s5.jpg",
		"url": "https://www.ikea.com/se/sv/p/tullsta-klaedsel-till-fatoelj-sjoelyckan-moerkbla-beige-rand-40635274/",
		"price": {
			"amount": 600,
			"currency": "SEK",
			"formatted": "600:-",
			"previous": null
		},
		"rating": null,
		"images": [
			{
				"url": "https://www.ikea.com/se/sv/images/products/tullsta-klaedsel-till-fatoelj-sjoelyckan-moerkbla-beige-rand__1547479_pe1020523_s5.jpg",
				"alt": "Randig tygfåtölj på nära håll; blå toner, högkvalitativ bomull, rena linjer, slät textur."
			}
		],
		"measurement": null,
		"badge": null,
		"colors": [],
		"categories": [
			"Soffor & fåtöljer",
			"Sofföverdrag & fåtöljöverdrag",
			"Andra soff- & fåtöljklädslar"
		],
		"variantCount": 2
	}
];

export const sampleProduct: Product = sampleProducts[0]!;
